version: 0.1

phases:
  install:
    on-failure: ABORT
    commands:
      - npm install -g @angular/cli@latest
    finally:
      - npm install
    # steps:
  build:
    on-failure: ABORT
    commands:
      - ng build
