version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - npm install -g @angular/cli@latest
    finally:
      - npm install
    # steps:
  build:
    on-failure: ABORT
    commands:
      - ng build
artifacts:
  files:
    - dist/lineups_gg/*
    - dist/lineups_gg/browser/*
  discard-paths: yes
